
```{r}
library(tidyverse)
```

load in raw data

```{r}
games <- read_csv("data-raw/games.csv")

atbats <- read_csv("data-raw/atbats.csv")

pitches <- read_csv("data-raw/pitches.csv")

merged_data <- read_csv("data-clean/test_clean.csv")
```

understanding a single game

```{r}
atbats_one_game <- 
	atbats %>% 
	filter(g_id == games$g_id[1]) %>% 
	mutate(g_id = as.character(g_id), ab_id = as.character(ab_id)) %>% 
	select(g_id, ab_id, everything())

merged_data_one_game <- 
	merged_data %>% 
	filter(g_id == games$g_id[1]) %>% 
	mutate(g_id = as.character(g_id), ab_id = as.character(ab_id)) %>% 
	select(g_id, ab_id, everything())

pitches_one_game <- 
	pitches %>% 
	filter(ab_id %in% atbats_one_game$ab_id) %>% 
	mutate(ab_id = as.character(ab_id)) %>% 
	select(ab_id, pitch_num, everything())

pitches_one_game %>% View()
```

```{r}
pitches_one_game %>% 
  count(pitch_type)
```


creating the dataframe

```{r}
df_final <- select(merged_data_one_game, pitch_type, s_count, b_count, pitch_num, ab_id)

df_final <-
  df_final %>% 
  mutate(fastball = case_when(is.na(pitch_type) ~ "N/A",
                                      pitch_type == "FF" ~ "yes",
                                      pitch_type == "FT" ~ "yes",
                                      TRUE ~ "no"))


df_final <- 
    df_final %>%
    mutate(last_ff_not = lag(case_when(is.na(pitch_type) ~ "N/A",
                                      pitch_type == "FF" ~ "FF",
                                      pitch_type == "FT" ~ "FF",
                                      pitch_type == "FC" ~ "FF",
                                      pitch_type == "CU" ~ "CU/SL",
                                      pitch_type == "SL" ~ "CU/SL",
                                      pitch_type == "CH" ~ "CH",
                                      TRUE ~ "OTHER"), 1))
 
df_final <- select(df_final,-c(pitch_type))  

```

data visualization and analysis

```{r}
# ggplot(data = df_final) +
  # geom_point(mapping = aes(x = s_count, y = ff_not))

# ggplot(data = merged_data_one_game) +
 # geom_bar(mapping = aes(x = pitch_type, y = stat(prop), group =1 ))

pitches_one_game %>% 
  count(pitch_type)
  print(pitch_num)
  
first_pitch <-
  df_final %>% 
    filter(pitch_num == 1)
  
one_strike <-
  df_final%>% 
    filter(s_count == 1)

two_strikes <-
  df_final%>% 
    filter(s_count == 2)

three_balls <-
  df_final%>% 
    filter(b_count == 3)

full_count <-
  df_final%>% 
    filter(b_count == 3 & s_count == 2)

one_strike %>%
  count(fastball)

two_strikes %>% 
  count(fastball)

three_balls %>% 
  count(fastball)

full_count %>% 
  count(fastball)

first_pitch %>%
  count(fastball)

df_final %>%
  count(fastball)
  
test_model <- lm()


```

